/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10: {
    WeSplit: {
      address: "0x0231f8e18af63f90483312db5347886ede54189e",
      abi: [
        {
          type: "constructor",
          inputs: [
            {
              name: "_pythAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "_fxUsdEurFeed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_ethUsdFeed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_usdcUsdFeed",
              type: "bytes32",
              internalType: "bytes32",
            },
            {
              name: "_btcUsdFeed",
              type: "bytes32",
              internalType: "bytes32",
            },
          ],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "contributeSplit",
          inputs: [
            {
              name: "splitId",
              type: "bytes4",
              internalType: "bytes4",
            },
            {
              name: "username",
              type: "string",
              internalType: "string",
            },
            {
              name: "amount",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [],
          stateMutability: "payable",
        },
        {
          type: "function",
          name: "getSplit",
          inputs: [
            {
              name: "splitId",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "",
              type: "tuple",
              internalType: "struct WeSplit.Split",
              components: [
                {
                  name: "requesterAddress",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "tokenAddress",
                  type: "address",
                  internalType: "address",
                },
                {
                  name: "fiatAmount",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "currency",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "description",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "verified",
                  type: "bool",
                  internalType: "bool",
                },
                {
                  name: "contributors",
                  type: "tuple[]",
                  internalType: "struct WeSplit.Contributor[]",
                  components: [
                    {
                      name: "username",
                      type: "string",
                      internalType: "string",
                    },
                    {
                      name: "contributed",
                      type: "uint256",
                      internalType: "uint256",
                    },
                    {
                      name: "withdrawn",
                      type: "uint256",
                      internalType: "uint256",
                    },
                    {
                      name: "toContribute",
                      type: "uint256",
                      internalType: "uint256",
                    },
                  ],
                },
              ],
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "getUserSplits",
          inputs: [
            {
              name: "user",
              type: "address",
              internalType: "address",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4[]",
              internalType: "bytes4[]",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "requestSplit",
          inputs: [
            {
              name: "fiatAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "tokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "currency",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "contributors",
              type: "tuple[]",
              internalType: "struct WeSplit.Contributor[]",
              components: [
                {
                  name: "username",
                  type: "string",
                  internalType: "string",
                },
                {
                  name: "contributed",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "withdrawn",
                  type: "uint256",
                  internalType: "uint256",
                },
                {
                  name: "toContribute",
                  type: "uint256",
                  internalType: "uint256",
                },
              ],
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "splitWithdraw",
          inputs: [
            {
              name: "splitId",
              type: "bytes4",
              internalType: "bytes4",
            },
            {
              name: "priceUpdate",
              type: "bytes[]",
              internalType: "bytes[]",
            },
          ],
          outputs: [],
          stateMutability: "nonpayable",
        },
        {
          type: "function",
          name: "splits",
          inputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          outputs: [
            {
              name: "requesterAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "tokenAddress",
              type: "address",
              internalType: "address",
            },
            {
              name: "fiatAmount",
              type: "uint256",
              internalType: "uint256",
            },
            {
              name: "currency",
              type: "string",
              internalType: "string",
            },
            {
              name: "description",
              type: "string",
              internalType: "string",
            },
            {
              name: "verified",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "function",
          name: "userSplits",
          inputs: [
            {
              name: "",
              type: "address",
              internalType: "address",
            },
            {
              name: "",
              type: "uint256",
              internalType: "uint256",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bytes4",
              internalType: "bytes4",
            },
          ],
          stateMutability: "view",
        },
        {
          type: "event",
          name: "SplitContributed",
          inputs: [],
          anonymous: false,
        },
        {
          type: "event",
          name: "SplitRequested",
          inputs: [
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "splitId",
              type: "bytes4",
              indexed: false,
              internalType: "bytes4",
            },
          ],
          anonymous: false,
        },
        {
          type: "event",
          name: "SplitWithdrawn",
          inputs: [
            {
              name: "requester",
              type: "address",
              indexed: true,
              internalType: "address",
            },
            {
              name: "splitId",
              type: "bytes4",
              indexed: true,
              internalType: "bytes4",
            },
            {
              name: "amount",
              type: "uint256",
              indexed: false,
              internalType: "uint256",
            },
          ],
          anonymous: false,
        },
      ],
      inheritedFunctions: {},
      deploymentFile: "run-1748715959.json",
      deploymentScript: "Deploy.s.sol",
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
